# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24f926d2f3ea2868351e68baa9642d7ba06bab4a27e76e0d38db87e87d5358f98ec6ad5d4cbbbeb993267070ae81128a6d9cca1b1926c9fc0c4fd44f1ddbb331

test:
  secret_key_base: b008a93e0a77f430162fe2ee59712b8b2f29de02ac8c342b62261a53a11c2b968c7bbf83c49b43061f33e96f7a28be401ffa75950488761e7ea2ae4f266a260d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
